import { useNavigate } from 'react-router-dom';
import { HeroSection } from '../components/home/HeroSection';
import { SubjectCard } from '../components/home/SubjectCard';
import { SUBJECTS } from '../data/metadata';
import { useWeakAreas } from '../hooks/useWeakAreas';
import { useRegion } from '../hooks/useRegion';

const QUESTION_COUNTS: Record<string, number> = {
  maths: 100,
  english: 80,
  verbal: 115,
  nonverbal: 75,
};

export function Home() {
  const { getWeakTopics } = useWeakAreas();
  const navigate = useNavigate();
  const weakTopics = getWeakTopics();
  const { region } = useRegion();

  return (
    <div>
      <HeroSection />

      {/* Weak areas banner */}
      {weakTopics.length > 0 && (
        <div className="bg-amber-50 dark:bg-amber-900/20 border-y border-amber-200 dark:border-amber-700 py-4 px-4">
          <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-start sm:items-center gap-3">
            <span className="text-xl">📊</span>
            <div className="flex-1">
              <span className="font-bold text-amber-800 dark:text-amber-300">Based on your last session, focus on: </span>
              <span className="text-amber-700 dark:text-amber-400">
                {weakTopics.slice(0, 3).map((t) => t.topic.replace(/-/g, ' ')).join(', ')}
              </span>
            </div>
            <button
              onClick={() => navigate('/quiz')}
              className="btn-primary text-sm py-2 px-4 whitespace-nowrap"
            >
              Start targeted practice →
            </button>
          </div>
        </div>
      )}

      {/* Subject grid */}
      <section className="max-w-6xl mx-auto px-4 py-14" id="subjects">
        <div className="text-center mb-10">
          <h2 className="text-3xl font-extrabold text-primary dark:text-blue-300 mb-2">Choose Your Subject</h2>
          <p className="text-gray-500 dark:text-slate-400">
            Practise the subjects tested in {region.name} ({region.examBoards.join(' / ')}), or take a mixed paper.
          </p>
        </div>
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {SUBJECTS.map((s) => (
            <SubjectCard key={s.id} subject={s} questionCount={QUESTION_COUNTS[s.id] || 80} />
          ))}
        </div>
      </section>

      {/* How it works */}
      <section className="bg-white dark:bg-slate-800 py-14 px-4" id="how-it-works">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-10">
            <h2 className="text-3xl font-extrabold text-primary dark:text-blue-300 mb-2">Two Ways to Practise</h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {/* Free mode */}
            <div className="card border-2 border-blue-100 dark:border-blue-800">
              <div className="text-4xl mb-3">🔒</div>
              <h3 className="text-xl font-extrabold text-primary dark:text-blue-300 mb-3">Free Mode</h3>
              <ul className="space-y-2 text-sm text-gray-600 dark:text-slate-300">
                {[
                  '300+ hand-crafted, exam-style questions',
                  'Works offline after first load',
                  'Aligned with GL Assessment format',
                  'No account or sign-up required',
                  'Instant results with explanations',
                ].map((item) => (
                  <li key={item} className="flex items-start gap-2">
                    <span className="text-emerald-500 mt-0.5">✓</span>
                    {item}
                  </li>
                ))}
              </ul>
            </div>

            {/* AI mode */}
            <div className="card border-2 border-amber-200 dark:border-amber-700">
              <div className="text-4xl mb-3">✨</div>
              <h3 className="text-xl font-extrabold text-secondary mb-3">AI Mode</h3>
              <ul className="space-y-2 text-sm text-gray-600 dark:text-slate-300">
                {[
                  'Fresh questions generated by Claude AI',
                  'Never the same paper twice',
                  'Adapts to your chosen difficulty',
                  'Requires Anthropic API key',
                  'Add key in ⚙️ Settings',
                ].map((item) => (
                  <li key={item} className="flex items-start gap-2">
                    <span className="text-amber-500 mt-0.5">✦</span>
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Schools strip */}
      <section className="bg-primary dark:bg-slate-900 py-8 px-4 overflow-hidden">
        <div className="max-w-6xl mx-auto">
          <p className="text-center text-blue-200 text-sm font-semibold mb-4 uppercase tracking-wider">
            {region.flag} Preparing students for {region.name} grammar schools
          </p>
          <div className="flex gap-6 overflow-x-auto pb-2 scrollbar-hide">
            {region.notableSchools.map((school) => (
              <div
                key={school.name}
                className="flex-shrink-0 bg-white/10 rounded-xl px-4 py-2 text-center"
              >
                <p className="text-white text-sm font-semibold whitespace-nowrap">{school.name}</p>
                <p className="text-blue-300 text-xs">{school.area}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
